AllCops:
  Exclude:
    - 'bin/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 20 # default: 15

Metrics/ClassLength:
  Enabled: false # todo
  Max: 100 # default: 100

Metrics/CyclomaticComplexity:
  Enabled: false # todo
  Max: 10 # default: 6

Metrics/LineLength:
  Enabled: false # todo
  Max: 100 # default: 80

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
  Max: 12 # default: 10

Metrics/PerceivedComplexity:
  Enabled: false # todo
  Max: 10 # default: 7

Style/AccessModifierIndentation:
  EnforcedStyle: indent
  SupportedStyles:
    - outdent
    - indent

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/ExtraSpacing:
  AllowForAlignment: false

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstParameterIndentation:
  EnforcedStyle: consistent

Style/FrozenStringLiteralComment:
  Enabled: true

Style/IndentArray:
  EnforcedStyle: consistent

Style/IndentHash:
  EnforcedStyle: consistent

Style/MethodCallWithArgsParentheses:
  Enabled: true # false by default
  Exclude:
    - "config/routes.rb"
    - "config/routes/*"
    - "Gemfile"
    - "**/*.gemspec"
  IgnoreMacros: true
  IgnoredMethods:
    - include
    - load
    - print
    - puts
    - raise
    - require
    # rake
    - desc
    - namespace
    - task
    # swagger
    - key
    - operation
    - property
    - response
    - security_definition
    - swagger_path
    - swagger_schema

Style/ModuleFunction:
  Enabled: false

Style/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceBeforeFirstArg:
  AllowForAlignment: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableNumber:
  EnforcedStyle: snake_case
